MetaMask/api-specs

- methods/wallet_switchEthereumChain.json
Specifies the `wallet_switchEthereumChain` JSON-RPC method. 
Note: This should only be merged after the feature ships.
> feat: add wallet_switchEthereumChain

- methods/personal_sign.json
Improving `personal_sign` documentation in two ways:
- Include link to minimal encoding example
- Document the need to connect the account first
> Add link to encoding example

- methods/wallet_watchAsset.json
wallet_watchAsset symbol takes 11 characters, updated the description to reflect that.
Fixes https://github.com/MetaMask/metamask-extension/issues/7567
> Changed wallet_watchAsset description to 11 characters

- methods/wallet_addEthereumChain.json
this updates them to be inline with latest + this related PR that will go in soon: https://github.com/MetaMask/metamask-extension/pull/15201/files#diff-b3485a1ea9943fd380364f73a53295289f2ccd3817423d4f245b5102f8620b3cR272
> Update wallet_addEthereumChain errors

- merge-openrpc.js
this prevents `engine_` apis from showing up in the playground:
`engine_` namespaces is only for communication between an Ethereum Node (like geth) and a beacon chain node.
> Ignore `engine_` apis from ethereum execution APIs spec

- merge-openrpc.js
- openrpc.json
fixes #155
fixes #148
fixes #146
fixes #147
> Fixed schema to better render in the docs side + removed createAccessList

- openrpc.json
This PR implements the changes to `wallet_watchAsset` as proposed in [MIP-1](https://github.com/MetaMask/metamask-improvement-proposals/pull/1).
> MIP-1 proposed watch asset changes

- openrpc.json
Adds a preliminary description for the MetaMask JSON-RPC API index page.
> Add description for index page

- openrpc.json
This pull request adds the "wallet_revokePermissions" JSON-RPC method, which allows revoking permissions from the current domain. It provides the flexibility to revoke all permissions for a specified permission or revoke permissions for specific caveats like account addresses.
- Add the "wallet_revokePermissions" method to the OpenRPC Doc.
> Wallet revoke permissions

- openrpc.json
Add deprecation label and note to `eth_decrypt` and `eth_getEncryptionPublicKey`. Fixes https://github.com/MetaMask/metamask-docs/issues/1018.
> Add deprecation label to decryption methods

- openrpc.json
This PR Changes `revokePermissions` to return null in all cases. Goes along with this PR in extension: https://github.com/MetaMask/metamask-extension/pull/22074
> Changed revokePermissions result type to be null

- openrpc.json
`wallet_addEthereumChain` requires `chainName`, `nativeCurrency` and `rpcUrls`. See that we enforce this [here](https://github.com/MetaMask/metamask-extension/blob/10996f0aaaf3a1d469cd79942c789e07152ad8f7/app/scripts/lib/rpc-method-middleware/handlers/add-ethereum-chain.js#L186). Currently the spec suggests that they are optional.
> Fix `wallet_addEthereumChain` request

- openrpc.json
Add reference to MIP-2 and note that the method is only available for the extension. See https://github.com/MetaMask/metamask-docs/issues/1020.
> Add info to `wallet_revokePermissions` description

- openrpc.json
Cleans up some inaccurate descriptions: `chainName` and `nativeCurrency` are not optional params for `wallet_addEthereumChain`. `name` is not a required key in the `nativeCurrency` object.
> More addEthereumChain spec fixes

- openrpc.json
Document Snap JSON-RPC API methods that are callable by dapps:
- `wallet_getSnap`
- `wallet_requestSnaps`
- `wallet_snap`
- `wallet_invokeSnap`
Also add example to `wallet_requestPermissions` for requesting the `wallet_snap` permission.
Quick preview: Paste contents of this file [`snaps-openrpc.json`](https://github.com/MetaMask/api-specs/files/14004467/snaps-openrpc.json) into https://playground.open-rpc.org/.
Fixes https://github.com/MetaMask/metamask-docs/issues/1091
> Document Snap `wallet_*` methods

- openrpc.yaml
Specify the fact that MetaMask does not currently display the iconUrls supplied in `wallet_addEthereumChain`.
> Adjust iconUrls param description

- openrpc.yaml
Partially closes https://github.com/MetaMask/metamask-docs/issues/1195
Updates language for restricted methods to be less narrow. Follow up to @jiexi restricted methods [PR](https://github.com/MetaMask/api-specs/pull/195)
> Update restricted text

- openrpc.yaml
Convert native currency decimal property `min` property to `minimum`.
> Convert native currency decimal property min property to minimum

- openrpc.yaml
This is to remove added examples that are throwing errors in the published docs. Related to the following methods:
`wallet_getPermissions`
`wallet_registerOnboarding`
> Remove example parameters that are throwing errors

- merge-openrpc.js
- multichain/openrpc.yaml
- src/index.ts
- transport/openrpc.yaml
> Added Transport OpenRPC Document for the MultiChain API

- openrpc.yaml
Fixes https://github.com/MetaMask/api-specs/issues/234
> fix: personal_sign is 65 bytes long (not 129 bytes)

- openrpc.yaml
This PR:
- Fixes the description and schema for `wallet_scanQRCode` (the method expects a single regex string, not an array)
- Fixes the example for `eth_decrypt`, adding in the required encrypted message.
> Fix `wallet_scanQRCode` and `eth_decrypt`

- openrpc.yaml
we only support logs and newHeads:
https://github.com/MetaMask/eth-json-rpc-filters/blob/main/subscriptionManager.js#L39-L49
> fix: remove unsupported filter types

- openrpc.yaml
The `TypedData` parameter is throwing an error on the current reference:
And the new reference:
This PR adds the required `items` property for the `EIP712Domain` array schema.
> Fix TypedData schema

- merge-openrpc.js
see here for more info: https://github.com/MetaMask/metamask-extension/issues/24225
we can enable these again when that issue is resolved
> fix: filter unsupported methods

- merge-openrpc.js
`eth_blobBaseFee` is not supported:
```json
{
"code": -32601,
"message": "The method \"eth_blobBaseFee\" does not exist / is not available.",
"data": {
"origin": "https://docs.metamask.io",
"cause": null
}
}
```
> Filter out `eth_blobBaseFee`

- multichain/openrpc.yaml
fixes https://github.com/MetaMask/MetaMask-planning/issues/3335
> Added revokeSession + add description to getSession

- merge-openrpc.js
- openrpc.yaml
This PR:
- Adds a new "Multichain API" tag to MetaMask-specific methods according to the [Multichain API mapping](https://docs.google.com/spreadsheets/d/1W13nar4qLffP7nFoVitpGCvKgquTw8rFHaVjDHmbK0w/edit?usp=sharing).
- Updates `merge-openrpc.js` to add the "Multichain API" tag to all methods imported and filtered from Ethereum's Execution API.
- Simplifies the API description. The API reference landing page on the docs site now uses a [Markdown index page](https://github.com/MetaMask/metamask-docs/pull/1623/files#diff-363d49245209b3ea4b5da0b7a9c73432a28656c3790bac7859ecefdf7b16d8e5) as its source.
> Add multichain tag

- openrpc.yaml
Since we've migrated to v2 of the OpenRPC spec parser for the API reference documentation, there are some missing/inconsistent/confusing details displayed in the rendered docs. This PR tweaks the spec param names, descriptions, etc. for the following methods to make the rendered docs more clear and consistent:
- `wallet_addEthereumChain`
- `wallet_switchEthereumChain`
- `wallet_getPermissions`
- `wallet_requestPermissions`
- `wallet_revokePermissions`
- `personal_sign`
The remaining methods will be addressed in future PRs.
Fixes #278 
See https://github.com/MetaMask/metamask-docs/issues/1778
> Fix spec for doc rendering (Part 1)

- multichain/openrpc.yaml
There's a misformat that is causing the results property to end up in a separate item unintentionally
> fix wallet create session unsupported scopes result example typo

- openrpc.yaml
This PR is a followup to #277. This tweaks the spec param names, descriptions, etc. for the following methods to make the rendered docs more clear and consistent:
- `eth_signTypedData_v4`
- `wallet_registerOnboarding`
- `wallet_watchAsset`
- `wallet_scanQRCode`
- `eth_requestAccounts`
- `eth_accounts`
- `eth_sendTransaction`
The remaining methods will be addressed in future PRs.
See https://github.com/MetaMask/metamask-docs/issues/1778
> Fix spec for doc rendering (Part 2)

- openrpc.yaml
Reverts MetaMask/api-specs#201 due to `wallet_swapAsset` not being live yet.
> Revert "wallet_swapAsset v1"

- multichain/openrpc.yaml
Blocking solana accountChanged event PR: https://github.com/MetaMask/metamask-extension/pull/30949
> add empty sessionProperties values as expected return from wallet_createSession
