MetaMask/api-specs

metamask-openrpc.json

- also reorder document so wallet_ methods are at the top

add ethereum chain to openrpc document

---

.github/workflows/create-release-pr.yml
.github/workflows/publish-release.yml

This adds extra publish steps to publish each version and a `latest` version folder to github pages.

Added extra publish steps for gh-pages

---

.github/workflows/publish-release.yml

fixes #93 
gh-pages action doesnt support subdir properly but this gh-pages action does and was audited already so we can use it.

Fixed deploy for latest

---

methods/wallet_addEthereumChain.json

Fixed example for xdai chain pointing to dead url

---

metamask-openrpc.json

Headings help users and search engines to read and understand text and content on a given page, we should be a bit more descriptive on the [MetaMask API Playground page](https://metamask.github.io/api-playground/api-documentation)
This is one of two changes to try and provide a better set of headings and text and use headings and text better on this page.
Beyond this, I will propose changes to the actual HTML structure of the page. h1 at the top instead of h6 and possibly change the heading where this text is displayed to a paragraph or keep it as an h2...

Update metamask-openrpc.json with more descriptive text

---

openrpc.json

add eth_signTypedData_v4

---

openrpc.json

Edit API docs, updating some summaries, descriptions, names, etc. for consistency, clarity, and conciseness. Also add "Restricted" and "Mobile" tags. There are still several methods and examples missing, see #124.

Edit API docs

---

openrpc.json

Update a broken rpcURL in the example for addEthereumChain to fix #128

update broken rpcURL for addEthereumChain

---

openrpc.json

Adds missing method `eth_requestAccounts`
fixes #101

Added eth_requestAccounts

---

openrpc.json

Add wallet_scanQRCode specs (based off of the [manual reference](https://docs.metamask.io/wallet/reference/rpc-api/#wallet_scanqrcode) in the docs).

Doc wallet_scanQRCode

---

openrpc.json

Edit descriptions on some methods to better fit the documentation.

Edit descriptions

---

openrpc.yaml

- **Remove duplicate content** - Delete repeated content and clarifying wording of description to remove the use of "MAY"

Remove duplicates

---

openrpc.yaml

Adding examples for the following methods:

Add examples 

---

openrpc.yaml

Fixed eth_accounts example params

---

openrpc.yaml

Fix eth_requestAccounts example

---

openrpc.yaml

Remove Snaps methods and references as part of https://github.com/MetaMask/metamask-docs/issues/1283

remove Snaps methods

---

.github/workflows/publish-docs.yml
.github/workflows/publish-release.yml
package.json
scripts/get.sh
scripts/prepack.sh

Add npm publish to gh actions workflow

---

.github/workflows/publish-release.yml

See here for more info: https://github.com/MetaMask/api-specs/pull/224/files#r1583576395

Fixed publish release to be on main branch instead

---

openrpc.yaml

Add Improvements to JSON Schema required for the interactive params table in the Metamask Docs reference page.

feat: ACT-1472 - Add Improvements for JSON Schema

---

multichain/openrpc.yaml

fix: remove unused multichain error codes

---

multichain/openrpc.yaml

fixes: https://github.com/MetaMask/MetaMask-planning/issues/3334

Added getSession

---

openrpc.yaml

This api-spec is a following work of the MIP of wallet_swapAsset: https://github.com/MetaMask/metamask-improvement-proposals/pull/25

wallet_swapAsset v1
